var ch = {
	"home" : {
		"welcome" : "Calendars to delight your guests",
		"gStarted" : "开始使用",
		"dBoard" : "开始",
		"whyUse" : ["规划和组织活动", " 方便 快捷 省时间", "制作独特的入场券", "创建和打印客人姓名卡", "方便客人签到", "同时在不同地方或者时间运作", "随时随地查看和管理访客名单", "查看活动的统计信息", "衡量您的活动的成本，收益和影响"],
		"logInInfo" : "登录以开始",
		"logOut" : "退出"
	},
	"nameBadge" : {
		"title" : "日历创建者",
		"content" : "输入",
		"chg" : "添加内容",
		"enter" : "确定",
		"preview" : "预览",
		"totNum" : "需要打印的姓名卡个数为",
		"cAndI" : "请在打印时确认打印的背景颜色和图像",
		"dSided" : "双面打印",
		"sSided" : "单面打印",
		"select" : "选择客户的图片",
		"getDeal" : "扫描获得折扣",
		"eMsg" : "输入个性化消息",
		"eBiz" : "输入公司信息",
		"genAt" : "设计姓名卡",
		"bizNameInst" : "输入商家名称",
		"pNum" : "电话号码",
		"logo" : "images/logo-ch.png",
		"editDeal" : "添加/更改促销",
		"editCal" : "编辑日历",
		"dealDesc" : "关于促销",
		"dealSavings" : "多少储蓄/他们会得到什么",
		"dealStart" : "促销开始",
		"dealEnd" : "促销结束",
		"submitDeal" : "添加促销",
		"selectLogo" : "上传标志",
		"dealAddUp" : "您在此处添加的促销是客户在日历中扫描qr代码时看到的。将为您的促销活动创建一个新网站",
		"dealAddDown" : "点击提交将打开一个新窗口和您的促销。这是客户在扫描代码时看到的",
		"comingSoon" : "促销即将推出"
	}
};
