var ch = {
    "home": {
        "welcome": "Calendars to delight your guests",
        "gStarted": "开始使用",
        "dBoard": "开始",
        "whyUse": ["规划和组织活动", " 方便 快捷 省时间", "制作独特的入场券", "创建和打印客人姓名卡", "方便客人签到", "同时在不同地方或者时间运作", "随时随地查看和管理访客名单", "查看活动的统计信息", "衡量您的活动的成本，收益和影响"],
        "logInInfo": "登录以开始",
        "logOut": "退出"
    },
    "nameBadge": {
        "title": "日历创建者",
        "content": "输入",
        "chg": "添加内容",
        "enter": "确定",
        "preview": "预览",
        "totNum": "需要打印的姓名卡个数为",
        "cAndI": "请在打印时确认打印的背景颜色和图像",
        "dSided": "双面打印",
        "sSided": "单面打印",
        "select": "选择客户的图片",
        "getDeal": "扫描获得折扣",
        "eMsg": "输入个性化消息",
        "eBiz": "输入公司信息",
        "genAt": "设计姓名卡",
        "bizNameInst": "输入商家名称",
        "pNum": "电话号码",
        "logo": "images/logo-ch.png",
        "editDeal": "添加/更改促销",
        "editCal": "编辑日历",
        "dealDesc": "关于促销",
        "dealSavings": "多少储蓄/他们会得到什么",
        "dealStart": "促销开始",
        "dealEnd": "促销结束",
        "submitDeal": "添加促销",
        "selectLogo": "上传标志",
        "dealAddUp": "您在此处添加的促销是客户在日历中扫描qr代码时看到的。将为您的促销活动创建一个新网站",
        "dealAddDown": "点击提交将打开一个新窗口和您的促销。这是客户在扫描代码时看到的",
        "comingSoon": "促销即将推出",
        "addGalItem": "最多可添加三个图片，以在宣传页面中显示"
    },
    "info": {
        "title": "日历制造商",
        "why": "好处",
        "intro": "我相信，如果客戶知道他們可以掃描它，以獲得在您的餐廳或酒店的交易，客戶會更傾向於保留日曆。我相信它也應該很容易改變出現的圖片。",
        "scan": "现在使用wechat扫描代码，以查看客户在扫描您的日历时会看到的示例。",
        "intro2": "这不仅仅是一个日历。你给客户一些可以互动的东西，同时也给他们一个回到你的方式。",
        "features": "功能",
        "featureIntro": "这不仅仅是日历生成器应用程序。该应用程序可以帮助您的客户通过扫描qr代码快速访问您提供的商业信息和促销活动。",
        "feature1": "创建和打印日历",
        "feature2": "添加促销，并获得您自己的独特网页",
        "feature3": "客户使用wechat扫描qr代码并查看您的商家页面",
        "feature4": "他们可以轻松地致电您的商家，并查看有关您商家的许多照片",
        "howTo": "如何使用",
        "howToIntro": "此工具可加快为每个客户生成唯一日历的过程。虽然日历很好，但它们可能不如由图形设计师或图形设计软件设计的日历那么好。如果日历看起来是日历最重要的事情，这个工具会工作，但图形设计软件可能会更好。",
        "howToSetup": "配置",
        "howToSetup1": "上传您的徽标",
        "howToSetup2": "输入您的商家名称",
        "howToSetup3": "输入您的商家简介的简短说明",
        "howToSetup4": "输入电话号码",
        "howToPrint": "如何打印",
        "howToPrint1": "选择客户图片",
        "howToPrint2": "为客户输入真棒消息",
        "howToPrint3": "验证qr代码将工作",
        "howToPrint4": "单击打印图标",
        "howToAddDeal": "添加/更改促销",
        "howToAddDeal1": "输入促销的名称",
        "howToAddDeal2": "輸入客戶將收到的促銷價值",
        "howToAddDeal3": "输入促销期（开始和结束日期）",
        "howToAddDeal4": "添加您的商家的一些图片，这些图片将显示在促销页面中",
        "howToAddDeal5": "保存促销以查看预览",
        "howToAddDeal6": "单击打印图标"
    }
};
