var en = {
	"home" : {
		"welcome" : "Calendars to delight your guests",
		"gStarted" : "Get started",
		"dBoard" : "Dashboard",
		"whyUse" : ["Manage Unlimited Events", "Design Tickets for each event", "Generate unique and imitation-proof tickets", "Speed up check-in process", "Check-in guests from multiple devices", "Run Events from multiple locations simulteneously", "View and manage guestlist on-the-go", "Get event summary and plan for future events", "Measure cost, benefits and impact of your event"],
		"logInInfo" : "Login to get started ",
		"logIn" : "Logout"
	},
	"nameBadge" : {
		"title" : "CALENDAR DESIGNER",
		"content" : "Content",
		"chg" : "Change the numbers below",
		"enter" : "Enter",
		"preview" : "Preview",
		"totNum" : "The number of badges you will print is",
		"cAndI" : "PLEASE PRINT WITH BACKGROUND COLOR AND IMAGES",
		"dSided" : "Print Double Sided",
		"sSided" : "Print Single Sided",
		"select" : "Select Customer's Picture",
		"getDeal" : "Scan For Deal",
		"eMsg" : "Enter a personalized message",
		"eBiz" : "Enter Business detail",
		"genAt" : "badges designed and generated at",
		"bizNameInst" : "Enter your company name",
		"pNum" : "Phone number",
		"logo" : "images/logo-en.png",
		"editDeal" : "Add/Change Deal",
		"editCal" : "Edit Calendar",
		"dealDesc" : "About deal",
		"dealSavings" : "How much savings/What will they get",
		"dealStart" : "Start Date",
		"dealEnd" : "End Date",
		"submitDeal" : "Submit Deal",
		"selectLogo" : "Upload Logo",
		"dealAddUp" : "The deal you add here is what customers see when they scan the qr code in the calendar. A unique web page with your deal will be generated",
		"dealAddDown" : "Clicking submit opens new window with your deal. This is what customers see when they scan the code",
		"comingSoon" : "Deal coming soon",
		"addGalItem" : "Add up to three images to show in your promo page"
	},
	"info" : {
		"title" : "Getting and keeping more customers",
		"why" : "Why",
		"intro" : "I believe that customers will be more inclined to keep the calendar if they know that they can scan it to get deals in your restuarant or hotel. I beleive that it should also be easy to change the pictures that show up.",
		"scan" : "Scan code now with wechat to see a sample of what customers will see.",
		"intro2" : "This is more than just a calendar. You're giving customers something that can interact with while also putting your business information out there.",
		"features" : "Features",
		"featureIntro" : "More than just a calendar genrator, this app helps your customers have quick access to your business information and deals about your business by scanning a qr code.",
		"feature1" : "Generate and print calendars",
		"feature2" : "Add deals/promo and get your own unique webpage",
		"feature3" : "Customers scan qr code with wechat and see your business page",
		"feature4" : "They can easily call and see pictures about your business",
		"howTo" : "How To",
		"howToIntro" : "This tool speeds up the process of generating unique calendars for each customer. While the calendars are good, they might not be as good as calendars designed by a graphics designer or with a graphics design software. If the way the calendar looks is the priority, this tool might not be the best for that.",
		"howToSetup" : "Setup",
		"howToSetup1" : "Upload you logo",
		"howToSetup2" : "Enter Business name",
		"howToSetup3" : "Enter description",
		"howToSetup4" : "Enter number",
		"howToPrint" : "Printing",
		"howToPrint1" : "Choose customer's picture",
		"howToPrint2" : "Enter a message for customer",
		"howToPrint3" : "verify that qr code will work",
		"howToPrint4" : "Print",
		"howToAddDeal" : "Add/Modify Deal",
		"howToAddDeal1" : "Enter name of deal",
		"howToAddDeal2" : "Enter what customers get",
		"howToAddDeal3" : "Enter duration (Start and end dates)",
		"howToAddDeal4" : "Add some pictures that will show in the deals page",
		"howToAddDeal5" : "Save and preview deal",
		"howToAddDeal6" : "Print"
	}
};
