var en = {
	"home" : {
		"welcome" : "Calendars to delight your guests",
		"gStarted" : "Get started",
		"dBoard" : "Dashboard",
		"whyUse" : ["Manage Unlimited Events", "Design Tickets for each event", "Generate unique and imitation-proof tickets", "Speed up check-in process", "Check-in guests from multiple devices", "Run Events from multiple locations simulteneously", "View and manage guestlist on-the-go", "Get event summary and plan for future events", "Measure cost, benefits and impact of your event"],
		"logInInfo" : "Login to get started ",
		"logIn" : "Logout"
	},
	"nameBadge" : {
		"title" : "CALENDAR DESIGNER",
		"content" : "Content",
		"chg" : "Change the numbers below",
		"enter" : "Enter",
		"preview" : "Preview",
		"totNum" : "The number of badges you will print is",
		"cAndI" : "PLEASE PRINT WITH BACKGROUND COLOR AND IMAGES",
		"dSided" : "Print Double Sided",
		"sSided" : "Print Single Sided",
		"select" : "Select Customer's Picture",
		"getDeal" : "Scan For Deal",
		"eMsg" : "Enter a personalized message",
		"eBiz" : "Enter Business detail",
		"genAt" : "badges designed and generated at",
		"bizNameInst" : "Enter your company name",
		"pNum" : "Phone number",
		"logo" : "images/logo-en.png",
		"editDeal" : "Add/Change Deal",
		"editCal" : "Edit Calendar",
		"dealDesc" : "About deal",
		"dealSavings" : "How much savings/What will they get",
		"dealStart" : "Start Date",
		"dealEnd" : "End Date",
		"submitDeal" : "Submit Deal",
		"selectLogo" : "Upload Logo",
		"dealAddUp" : "The deal you add here is what customers see when they scan the qr code in the calendar. A unique web page with your deal will be generated",
		"dealAddDown" : "Clicking submit opens new window with your deal. This is what customers see when they scan the code",
		"comingSoon" : "Deal coming soon"
	}
};
